version: '3.7'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: shop
                uid: 1000
        image: pet-shop
        container_name: pet-shop-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - '.:/var/www'
        networks:
            - pet-shop
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: pet-ship-mysql
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - './db:/var/lib/mysql'
        networks:
            - pet-shop
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    nginx:
        image: nginx:1.17-alpine
        container_name: pet-shop-nginx
        restart: unless-stopped
        ports:
            -   8000:80
        volumes:
            -   ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - pet-shop
networks:
    pet-shop:
        driver: bridge
