openapi: 3.0.0
info:
  title: Pet Shop API
  description: Pet Shop API Swagger Documentation
  version: 0.0.1

servers:
  - url: http://127.0.0.1:8000
    description: local server

security:
  - bearerAuth: []

tags:
  - name: "Admin"
    description: "Admin API endpoint"
  - name: "User"
    description: "User API endpoint"

paths:
  /api/v1/admin/login:
    post:
      tags:
        - Admin
      summary: Login to an Admin account
      requestBody:
        $ref: '#/components/requestBodies/LoginBody'
      responses:
        200:
          description: "Ok"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

  /api/v1/admin/logout:
    get:
      tags:
        - Admin
      summary: Logout from an Admin account
      operationId: "admin-logout"
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

  /api/v1/admin/create:
    post:
      tags:
        - Admin
      summary: Create an Admin account
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: "User first name"
                last_name:
                  type: string
                  description: "User last name"
                email:
                  type: string
                  description: "User email"
                password:
                  type: string
                  description: "User password"
                password_confirmation:
                  type: string
                  description: "User password"
                avatar:
                  type: string
                  description: "Avatar image UUID"
                address:
                  type: string
                  description: "User address"
                phone_number:
                  type: string
                  description: "User phone number"
                is_marketing:
                  type: string
                  description: "User marketing preferences"
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - avatar
                - address
                - phone_number
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

  /api/v1/admin/user-listing:
    get:
      tags:
        - Admin
      summary: List all users
      operationId: "admin-user-listing"
      parameters:
        - name: "page"
          required: false
          in: query
          schema:
            type: integer
        - name: "limit"
          required: false
          in: query
          schema:
            type: integer
        - name: "sortBy"
          required: false
          in: query
          schema:
            type: string
        - name: "desc"
          required: false
          in: query
          schema:
            type: boolean
        - name: "first_name"
          required: false
          in: query
          schema:
            type: string
        - name: "email"
          required: false
          in: query
          schema:
            type: string
        - name: "phone"
          required: false
          in: query
          schema:
            type: string
        - name: "address"
          required: false
          in: query
          schema:
            type: string
        - name: "created_at"
          required: false
          in: query
          schema:
            type: string
        - name: "marketing"
          required: false
          in: query
          schema:
            type: string
            enum:
              - 0
              - 1
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

  /api/v1/admin/user-edit/{uuid}:
    put:
      tags:
        - Admin
      summary: "Edit a User account"
      operationId: 'admin-user-edit'
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: "User first name"
                last_name:
                  type: string
                  description: "User last name"
                email:
                  type: string
                  description: "User email"
                password:
                  type: string
                  description: "User password"
                password_confirmation:
                  type: string
                  description: "User password"
                avatar:
                  type: string
                  description: "Avatar image UUID"
                address:
                  type: string
                  description: "User address"
                phone_number:
                  type: string
                  description: "User phone number"
                is_marketing:
                  type: string
                  description: "User marketing preferences"
              required:
                - first_name
                - last_name
                - email
                - password
                - password_confirmation
                - address
                - phone_number
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

  /api/v1/admin/user-delete/{uuid}:
    delete:
      tags:
        - Admin
      summary: "Delete a User account"
      operationId: "admin-user-delete"
      parameters:
        - name: uuid
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Page not found"
        422:
          description: "Unprocessable Entity"
        500:
          description: "Internal server error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      scheme: bearer
      bearerFormat: JWT

  responses:
    200:
      description: "Ok"
    401:
      description: "Unauthorized"
    404:
      description: "Page not found"
    422:
      description: "Unprocessable Entity"
    500:
      description: "Internal server error"

  requestBodies:
    LoginBody:
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            type: object
            properties:
              email:
                type: string
                default: admin@buckhill.co.uk
              password:
                type: string
                default: password
            required:
              - email
              - password
