openapi: 3.0.0
info:
  title: Pet Shop API
  description: Pet Shop API Swagger Documentation
  version: 0.1.9

servers:
  - url: http://127.0.0.1:8000/api
    description: local server

paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: